package leo.util.service.impl;

import java.text.SimpleDateFormat;
import java.util.Date;
//Generated by MyEclipse

import leo.util.service.iface.GetTime;

public class GetTimeImpl implements GetTime {
	
	public String getTime(){
		 Date nowTime=new Date();
			SimpleDateFormat time=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

			System.out.println(time.format(nowTime));
			return time.format(nowTime);
	}
	
	
}